### ISSUE TITLE
songidx problem

### ISSUE THREAD

**Issue by antagomir** [unilaiva/unilaiva-songbook#1]
Where I can find this binary ?

user@machine:~//wisdom$ ./compile_wisdom.sh 
ext_packages/bin/songidx binary not found! Aborted.

**Comment by unilarva** [comment]
The binary must be compiled as stated in README.md. See https://github.com/antagomir/wisdom#environment

**Comment by antagomir** [comment]
Ah, I missed that of course. Works like a charm now - tnx!

**Comment by unilarva** [comment]
Update: as of commit 0f20e1cc338c, the compilation step is not needed anymore. Instead, `luatex` binary must be found on the system.
